### ISSUE TITLE
Add use of System Preferences Icons

### ISSUE THREAD

**Issue by jameskirsop** [bartreardon/Dialog-public#18]
I'd like to be able to use an icon from System Preferences (eg, 'Users & Groups for password related notifications) but if I pass the path to the .prefpane I want to use the icon from (like I could do for an Application) I get an error.

```
201
ERROR: Image resource cannot be found : /System/Library/PreferencePanes/Accounts.prefPane
```

I believe this is the correct path to pass, but I may be wrong (and if so, it'd be useful for this to be added to the documentation).

**Comment by bartreardon** [comment]
Yup, it's possible. I'm only scanning for `.app` to process extracting the icon from the application bundle but it's perfectly doable to extract icons from any bundle type, including prefpanes. e.g.

![image](https://user-images.githubusercontent.com/3598965/117599450-31445900-b18d-11eb-9506-a5fc75f22e04.png)

Will look at other bundle types and add them in as well.
