### ISSUE TITLE
Button 2 Returns an exit code of 0

### ISSUE THREAD

**Issue by kdrwygvh** [bartreardon/Dialog-public#59]
When getting the output of a dialog command with --button2 enabled and clicked the exit code is always 0

**Comment by bartreardon** [comment]
Hi, can you verify this build is ok? [dialog-1.8.1.zip](https://github.com/bartreardon/Dialog-public/files/7455904/dialog-1.8.1.zip)

**Comment by bartreardon** [comment]
fixed in PR https://github.com/bartreardon/Dialog-public/pull/60 

release https://github.com/bartreardon/Dialog-public/releases/tag/v1.8.1

**Comment by kdrwygvh** [comment]
Yes, fixed. Thank you.

**Comment by mmsrvtwn** [comment]
I have this issue now with version 2.5.0.4768 🙁

**Comment by bartreardon** [comment]
@mmsrvtwn what's your script look like? testing here with the latest release and button 2 returns exit code 2 (macos 14.5)

**Comment by mmsrvtwn** [comment]
Sorry, it was my mistake. I had a variable between button click and query of the pressed button, which led to always getting the value 0.
